export const categoryConstants = {
    GET_ALL_CATEGORY_REQUEST: "GET_ALL_CATEGORY_REQUEST",
    GET_ALL_CATEGORY_SUCCESS: "GET_ALL_CATEGORY_SUCCESS",
    GET_ALL_CATEGORY_FAILURE: "GET_ALL_CATEGORY_FAILURE",
};

export const productConstants = {
    GET_PRODUCT_BY_SLUG_REQUEST: "GET_PRODUCT_BY_SLUG_REQUEST",
    GET_PRODUCT_BY_SLUG_SUCCESS: "GET_PRODUCT_BY_SLUG_SUCCESS",
    GET_PRODUCT_BY_SLUG_FAILURE: "GET_PRODUCT_BY_SLUG_FAILURE",
};

export const pageConstants = {
    GET_PRODUCT_PAGE_REQUEST: "GET_PRODUCT_PAGE_REQUEST",
    GET_PRODUCT_PAGE_SUCCESS: "GET_PRODUCT_PAGE_SUCCESS",
    GET_PRODUCT_PAGE_FAILURE: "GET_PRODUCT_PAGE_FAILURE",
};
